name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
         username: ${{ secrets.DOCKERHUB_USR }}
         password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build kube news 
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            3mmessias/kube-news:v${{ github.run_number }}
            3mmessias/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configuração do kubectl 
        shell: bash
        run: aws eks update-config --name eks-inersao-devops --region us-east-1
      - name: Deploy das Aplicações
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/deploy-kubenews.yaml
          images: |
            3mmessias/kube-news:v${{ github.run_number }}
