name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
         username: ${{ secrets.DOKERHUB_USR }}
         password: ${{ secrets.DOKERHUB_PWD }}
      - name: Docker Build kube news 
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dokerfile
          push: true
          tags: |
            3mmessias/kube-news:v${{ github.run_number }}
            3mmessias/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v3
      - name: Autenticar AWS CLI
        run: echo "Configurar o AWS CLI"
      - name: Configuração do kubectl 
        run: echo "Configurar o kubectl"
      - name: Deploy das Aplicações
        run: echo "Executar o comando Apply do kubectl nos arquivos de manifesto"
